module.exports = [
    { resolving: 0, data: null, count: 0, ws: null, hasFetched: false },
    { resolving: 1, data: null, count: 0, ws: null, hasFetched: false },
    { resolving: 2, data: null, count: 0, ws: null, hasFetched: false },
    { resolving: 3, data: null, count: 0, ws: null, hasFetched: false },
    { resolving: 3,
        data: 'fetch',
        count: 1,
        ws: null,
        hasFetched: true },
    { resolving: 2,
        data: 'fetch',
        count: 1,
        ws: null,
        hasFetched: true },
    { resolving: 2,
        data: 'udpate',
        count: 2,
        ws: null,
        hasFetched: true },
    { resolving: 1,
        data: 'udpate',
        count: 2,
        ws: null,
        hasFetched: true },
    { resolving: 1,
        data: 'delete',
        count: 3,
        ws: null,
        hasFetched: true },
    { resolving: 0,
        data: 'delete',
        count: 3,
        ws: null,
        hasFetched: true }
]
